# PhantomFuzzer Default Configuration

# General settings
general:
  log_level: INFO
  output_format: json
  max_threads: 10
  scan_timeout: 300  # seconds
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# Scanner settings
scanner:
  modes:
    - basic
    - ml_enhanced
    - stealth
    - full_attack
  default_mode: basic
  port_scan:
    enabled: true
    port_range: "1-1000"
    scan_type: "SYN"
  web_scan:
    crawl_depth: 3
    form_submission: true
    file_discovery: true
  api_scan:
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    parameter_testing: true

# Fuzzer settings
fuzzer:
  mutation_rate: 0.1
  max_mutations: 100
  strategies:
    - boundary_testing
    - type_confusion
    - injection
    - format_string
    - overflow
  input_types:
    - form_fields
    - url_parameters
    - headers
    - cookies
    - json_body
    - xml_data

# ML settings
ml:
  enabled: true
  models:
    vulnerability_classifier:
      path: "/data/training/models/vuln_classifier.h5"
      confidence_threshold: 0.7
    pattern_recognizer:
      path: "/data/training/models/pattern_rec.pkl"
      confidence_threshold: 0.6
    payload_generator:
      path: "/data/training/models/payload_gen.h5"
      temperature: 0.8
  training:
    batch_size: 32
    epochs: 20
    validation_split: 0.2
    early_stopping: true
  feedback:
    collect_results: true
    auto_retrain: false

# Stealth settings
stealth:
  browser_emulation: true
  random_delays:
    enabled: true
    min_delay: 0.5  # seconds
    max_delay: 3.0  # seconds
  ip_rotation:
    enabled: false
    proxy_list: "/data/proxies.txt"
  request_distribution:
    enabled: true
    max_rate: 10  # requests per second
  bandwidth_control:
    enabled: true
    max_bandwidth: 500  # KB/s

# Payload settings
payload:
  templates:
    enabled: true
    path: "/data/payloads/templates"
  custom_generation:
    enabled: true
    max_length: 1000
  effectiveness_testing:
    enabled: true
    metrics:
      - success_rate
      - evasion_rate
      - performance

# Wordlists
wordlists:
  usernames: "/data/wordlists/usernames/common.txt"
  passwords: "/data/wordlists/passwords/top10000.txt"
  directories: "/data/wordlists/directories/web-dirs.txt"
  endpoints: "/data/wordlists/endpoints/api-endpoints.txt"
  parameters: "/data/wordlists/parameters/web-params.txt"

# Reporting
reporting:
  formats:
    - json
    - html
    - pdf
  include:
    - summary
    - details
    - remediation
    - evidence
  severity_levels:
    - critical
    - high
    - medium
    - low
    - info

# API/Web Interface
api:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  authentication:
    enabled: true
    method: "jwt"
    secret_key_env: "API_SECRET_KEY"
  rate_limiting:
    enabled: true
    max_requests: 100
    period: 60  # seconds
